[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.web"

[deploy]
startCommand = "sh -c 'python manage.py migrate && gunicorn -k uvicorn.workers.UvicornWorker config.asgi:application --bind 0.0.0.0:${PORT:-8000} --workers 2 --timeout 120'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
