"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os, dj_database_url
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "dev")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "false").lower() == "true"

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "localhost").split(",")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ninja',         # Django Ninja
    'botapp.apps.BotappConfig',        # наше приложение бота
    'lavatop',       # Payment System (Lava.top)
    'dashboard.apps.DashboardConfig',  # Панель администратора
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASE_URL = os.getenv("DATABASE_URL")
if not DATABASE_URL:
    raise RuntimeError("Не задана переменная окружения DATABASE_URL")

DB_CONN_MAX_AGE = int(os.getenv("DB_CONN_MAX_AGE", "60"))
_ssl_required = (
    not DATABASE_URL.lower().startswith("sqlite")
    and "sslmode=disable" not in DATABASE_URL.lower()
)
DATABASES = {
    "default": dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=DB_CONN_MAX_AGE,
        ssl_require=_ssl_required,
    )
}

db_pool_mode = os.getenv("DB_POOL_MODE", "session").strip().lower()
if db_pool_mode == "transaction":
    DATABASES["default"]["CONN_MAX_AGE"] = 0  # соединение закрывается сразу после запроса
    DATABASES["default"]["DISABLE_SERVER_SIDE_CURSORS"] = True
    options = DATABASES["default"].get("OPTIONS", {}).copy()
    options.setdefault("sslmode", "require")
    # Используем prepared_statements=off, чтобы PgBouncer в transaction-режиме не падал
    extra_options = options.get("options", "")
    if "prepared_statements=off" not in extra_options:
        extra_options = f"{extra_options} prepared_statements=off".strip()
    options["options"] = extra_options
    DATABASES["default"]["OPTIONS"] = options

DATABASES["default"]["CONN_HEALTH_CHECKS"] = True


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
os.makedirs(STATIC_ROOT, exist_ok=True)
STATICFILES_DIRS = []
_extra_static_dirs = [
    BASE_DIR / 'miniapp' / 'static',
]
for static_dir in _extra_static_dirs:
    if static_dir.exists():
        STATICFILES_DIRS.append(static_dir)

WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = DEBUG

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Celery ---
CELERY_BROKER_URL = os.getenv("REDIS_URL")
CELERY_RESULT_BACKEND = os.getenv("REDIS_URL")
CELERY_TASK_ALWAYS_EAGER = False
CELERY_TASK_DEFAULT_QUEUE = "default"
CELERY_WORKER_CONCURRENCY = int(os.getenv("CELERY_WORKER_CONCURRENCY", "2"))
CELERY_WORKER_PREFETCH_MULTIPLIER = int(os.getenv("CELERY_WORKER_PREFETCH_MULTIPLIER", "1"))
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_TIME_LIMIT = int(os.getenv("CELERY_TASK_TIME_LIMIT", str(15 * 60)))
CELERY_TASK_SOFT_TIME_LIMIT = int(os.getenv("CELERY_TASK_SOFT_TIME_LIMIT", str(12 * 60)))

# --- Telegram/Gemini/Supabase ---
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
TG_WEBHOOK_SECRET  = os.getenv("TG_WEBHOOK_SECRET")
PUBLIC_BASE_URL    = os.getenv("PUBLIC_BASE_URL")
_csrf_origins_raw = os.getenv("CSRF_TRUSTED_ORIGINS", "")
CSRF_TRUSTED_ORIGINS = [
    origin.strip().rstrip("/")
    for origin in _csrf_origins_raw.split(",")
    if origin.strip()
]
if PUBLIC_BASE_URL:
    public_origin = PUBLIC_BASE_URL.rstrip("/")
    if public_origin and public_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(public_origin)
GEMINI_API_KEY     = os.getenv("GEMINI_API_KEY")
SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_SERVICE_ROLE_KEY")
SUPABASE_BUCKET = os.getenv("SUPABASE_BUCKET", "bot-images")
SUPABASE_VIDEO_BUCKET = os.getenv("SUPABASE_VIDEO_BUCKET", SUPABASE_BUCKET)

# --- Google Vertex AI ---
USE_VERTEX_AI = os.getenv("USE_VERTEX_AI", "false").lower() in ("true", "1", "yes")
GOOGLE_APPLICATION_CREDENTIALS_JSON = os.getenv("GOOGLE_APPLICATION_CREDENTIALS_JSON")
GCP_PROJECT_ID = os.getenv("GCP_PROJECT_ID")
GCP_LOCATION = os.getenv("GCP_LOCATION", "us-central1")
VERTEX_PROJECT_ID = os.getenv("VERTEX_PROJECT_ID", GCP_PROJECT_ID)
VERTEX_LOCATION = os.getenv("VERTEX_LOCATION", GCP_LOCATION or "us-central1")
NANO_BANANA_API_KEY = os.getenv("NANO_BANANA_API_KEY")

# --- OpenAI Sora ---
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
OPENAI_API_BASE = os.getenv("OPENAI_API_BASE", "https://api.openai.com/v1")
OPENAI_ORGANIZATION = os.getenv("OPENAI_ORGANIZATION")
OPENAI_PROJECT_ID = os.getenv("OPENAI_PROJECT_ID")
OPENAI_BETA_HEADER = os.getenv("OPENAI_BETA_HEADER", "video-generation=v1")
OPENAI_VIDEO_POLL_INTERVAL = int(os.getenv("OPENAI_VIDEO_POLL_INTERVAL", "5"))
OPENAI_VIDEO_POLL_TIMEOUT = int(os.getenv("OPENAI_VIDEO_POLL_TIMEOUT", str(15 * 60)))

_openai_request_timeout_raw = os.getenv("OPENAI_VIDEO_REQUEST_TIMEOUT")
OPENAI_VIDEO_REQUEST_TIMEOUT = float(_openai_request_timeout_raw) if _openai_request_timeout_raw else None

_openai_content_timeout_raw = os.getenv("OPENAI_VIDEO_CONTENT_TIMEOUT")
OPENAI_VIDEO_CONTENT_TIMEOUT = float(_openai_content_timeout_raw) if _openai_content_timeout_raw else None

# --- Kling Video API ---
KLING_API_KEY = os.getenv("KLING_API_KEY")
KLING_API_SECRET = os.getenv("KLING_API_SECRET")
KLING_ORGANIZATION_ID = os.getenv("KLING_ORGANIZATION_ID")
KLING_API_BASE_URL = os.getenv("KLING_API_BASE_URL", "https://api-singapore.klingai.com")
KLING_CREATE_ENDPOINT = os.getenv("KLING_CREATE_ENDPOINT", "/v1/video/generations")
KLING_STATUS_ENDPOINT = os.getenv("KLING_STATUS_ENDPOINT", "/v1/video/generations/{job_id}")
KLING_TEXT2VIDEO_ENDPOINT = os.getenv("KLING_TEXT2VIDEO_ENDPOINT")
KLING_IMAGE2VIDEO_ENDPOINT = os.getenv("KLING_IMAGE2VIDEO_ENDPOINT")
KLING_TEXT2VIDEO_STATUS_ENDPOINT = os.getenv("KLING_TEXT2VIDEO_STATUS_ENDPOINT")
KLING_IMAGE2VIDEO_STATUS_ENDPOINT = os.getenv("KLING_IMAGE2VIDEO_STATUS_ENDPOINT")
KLING_POLL_INTERVAL = int(os.getenv("KLING_POLL_INTERVAL", "5"))
KLING_POLL_TIMEOUT = int(os.getenv("KLING_POLL_TIMEOUT", str(12 * 60)))
KLING_REQUEST_TIMEOUT = os.getenv("KLING_REQUEST_TIMEOUT")
KLING_EXTRA_HEADERS = os.getenv("KLING_EXTRA_HEADERS")

# --- KIE AI proxy for Kling ---
KIE_API_KEY = os.getenv("KIE_API_KEY")
KIE_API_BASE_URL = os.getenv("KIE_API_BASE_URL", "https://api.kie.ai")
KIE_TEXT2VIDEO_MODEL = os.getenv("KIE_TEXT2VIDEO_MODEL", "kling/v2-5-turbo-text-to-video-pro")
KIE_IMAGE2VIDEO_MODEL = os.getenv("KIE_IMAGE2VIDEO_MODEL", "kling/v2-5-turbo-image-to-video-pro")
KIE_POLL_INTERVAL = int(os.getenv("KIE_POLL_INTERVAL", str(KLING_POLL_INTERVAL)))
KIE_POLL_TIMEOUT = int(os.getenv("KIE_POLL_TIMEOUT", str(KLING_POLL_TIMEOUT)))
KIE_REQUEST_TIMEOUT = os.getenv("KIE_REQUEST_TIMEOUT")

# --- Midjourney via KIE ---
MIDJOURNEY_KIE_API_KEY = os.getenv("MIDJOURNEY_KIE_API_KEY", KIE_API_KEY)
MIDJOURNEY_KIE_BASE_URL = os.getenv("MIDJOURNEY_KIE_BASE_URL", KIE_API_BASE_URL)
MIDJOURNEY_KIE_TEXT_MODEL = os.getenv("MIDJOURNEY_KIE_TEXT_MODEL", "midjourney/v6-text-to-image")
MIDJOURNEY_KIE_IMAGE_MODEL = os.getenv("MIDJOURNEY_KIE_IMAGE_MODEL", "midjourney/v6-image-to-image")
MIDJOURNEY_KIE_POLL_INTERVAL = int(os.getenv("MIDJOURNEY_KIE_POLL_INTERVAL", str(KIE_POLL_INTERVAL)))
MIDJOURNEY_KIE_POLL_TIMEOUT = int(os.getenv("MIDJOURNEY_KIE_POLL_TIMEOUT", str(KIE_POLL_TIMEOUT)))
MIDJOURNEY_KIE_REQUEST_TIMEOUT = os.getenv("MIDJOURNEY_KIE_REQUEST_TIMEOUT", KIE_REQUEST_TIMEOUT)

# --- Lava.top Payment ---
LAVA_WEBHOOK_SECRET = os.getenv("LAVA_WEBHOOK_SECRET")
LAVA_API_KEY = os.getenv("LAVA_API_KEY")
LAVA_FALLBACK_CHAT_ID = os.getenv("LAVA_FALLBACK_CHAT_ID", "283738604")
# Безопасная обработка PUBLIC_BASE_URL (может быть None в CI окружении)
PAYMENT_MINI_APP_URL = f"{PUBLIC_BASE_URL.rstrip('/')}/miniapp/" if PUBLIC_BASE_URL else None

# --- Sentry (опционально) ---
SENTRY_DSN = os.getenv("SENTRY_DSN")
if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.celery import CeleryIntegration
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration(), CeleryIntegration(monitor_beat_tasks=True)],
        traces_sample_rate=0.2, send_default_pii=False,
    )

# --- Error monitoring ---
ERROR_ALERT_CHAT_ID = os.getenv("ERROR_ALERT_CHAT_ID") or LAVA_FALLBACK_CHAT_ID
ERROR_ALERT_COOLDOWN = int(os.getenv("ERROR_ALERT_COOLDOWN", "300"))
ERROR_LOG_RETENTION_DAYS = int(os.getenv("ERROR_LOG_RETENTION_DAYS", "30"))

# --- Upload limits ---
# Поднимаем лимиты для WebApp: base64 изображений может быть крупным
DATA_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024  # 50 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024

# Test comment for Railway reconnect verification (deployment test)
# E2E test timestamp: 2025-11-18 19:40 (with Railway CLI verification)
# Final E2E test: 2025-11-18 20:11 (Railway API + CLI working)
