"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os, dj_database_url
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "dev")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "false").lower() == "true"

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "localhost").split(",")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ninja',         # Django Ninja
    'botapp.apps.BotappConfig',        # наше приложение бота
    'lavatop',       # Payment System (Lava.top)
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASES = {
    "default": dj_database_url.parse(os.getenv("DATABASE_URL"), conn_max_age=600, ssl_require=True)
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'miniapp', 'static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Celery ---
CELERY_BROKER_URL = os.getenv("REDIS_URL")
CELERY_RESULT_BACKEND = os.getenv("REDIS_URL")
CELERY_TASK_ALWAYS_EAGER = False
CELERY_TASK_DEFAULT_QUEUE = "default"

# --- Telegram/Gemini/Supabase ---
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
TG_WEBHOOK_SECRET  = os.getenv("TG_WEBHOOK_SECRET")
PUBLIC_BASE_URL    = os.getenv("PUBLIC_BASE_URL")
GEMINI_API_KEY     = os.getenv("GEMINI_API_KEY")
GEMINI_IMAGE_MODEL = os.getenv("GEMINI_IMAGE_MODEL", "gemini-2.5-flash-image")
GEMINI_IMAGE_MODEL_FALLBACK = os.getenv("GEMINI_IMAGE_MODEL_FALLBACK", "gemini-2.5-flash-image-preview")
SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_SERVICE_ROLE_KEY")
SUPABASE_BUCKET = os.getenv("SUPABASE_BUCKET", "bot-images")
SUPABASE_VIDEO_BUCKET = os.getenv("SUPABASE_VIDEO_BUCKET", SUPABASE_BUCKET)

# --- Google Vertex AI ---
USE_VERTEX_AI = os.getenv("USE_VERTEX_AI", "false").lower() in ("true", "1", "yes")
GOOGLE_APPLICATION_CREDENTIALS_JSON = os.getenv("GOOGLE_APPLICATION_CREDENTIALS_JSON")
GCP_PROJECT_ID = os.getenv("GCP_PROJECT_ID")
GCP_LOCATION = os.getenv("GCP_LOCATION", "us-central1")
VERTEX_PROJECT_ID = os.getenv("VERTEX_PROJECT_ID", GCP_PROJECT_ID)
VERTEX_LOCATION = os.getenv("VERTEX_LOCATION", GCP_LOCATION or "us-central1")

# --- OpenAI Sora ---
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
OPENAI_API_BASE = os.getenv("OPENAI_API_BASE", "https://api.openai.com/v1")
OPENAI_ORGANIZATION = os.getenv("OPENAI_ORGANIZATION")
OPENAI_PROJECT_ID = os.getenv("OPENAI_PROJECT_ID")
OPENAI_BETA_HEADER = os.getenv("OPENAI_BETA_HEADER", "video-generation=v1")
OPENAI_VIDEO_POLL_INTERVAL = int(os.getenv("OPENAI_VIDEO_POLL_INTERVAL", "5"))
OPENAI_VIDEO_POLL_TIMEOUT = int(os.getenv("OPENAI_VIDEO_POLL_TIMEOUT", str(15 * 60)))

_openai_request_timeout_raw = os.getenv("OPENAI_VIDEO_REQUEST_TIMEOUT")
OPENAI_VIDEO_REQUEST_TIMEOUT = float(_openai_request_timeout_raw) if _openai_request_timeout_raw else None

_openai_content_timeout_raw = os.getenv("OPENAI_VIDEO_CONTENT_TIMEOUT")
OPENAI_VIDEO_CONTENT_TIMEOUT = float(_openai_content_timeout_raw) if _openai_content_timeout_raw else None

# --- Kling Video API ---
KLING_API_KEY = os.getenv("KLING_API_KEY")
KLING_API_SECRET = os.getenv("KLING_API_SECRET")
KLING_ORGANIZATION_ID = os.getenv("KLING_ORGANIZATION_ID")
KLING_API_BASE_URL = os.getenv("KLING_API_BASE_URL", "https://api-singapore.klingai.com")
KLING_CREATE_ENDPOINT = os.getenv("KLING_CREATE_ENDPOINT", "/v1/video/generations")
KLING_STATUS_ENDPOINT = os.getenv("KLING_STATUS_ENDPOINT", "/v1/video/generations/{job_id}")
KLING_TEXT2VIDEO_ENDPOINT = os.getenv("KLING_TEXT2VIDEO_ENDPOINT")
KLING_IMAGE2VIDEO_ENDPOINT = os.getenv("KLING_IMAGE2VIDEO_ENDPOINT")
KLING_TEXT2VIDEO_STATUS_ENDPOINT = os.getenv("KLING_TEXT2VIDEO_STATUS_ENDPOINT")
KLING_IMAGE2VIDEO_STATUS_ENDPOINT = os.getenv("KLING_IMAGE2VIDEO_STATUS_ENDPOINT")
KLING_POLL_INTERVAL = int(os.getenv("KLING_POLL_INTERVAL", "5"))
KLING_POLL_TIMEOUT = int(os.getenv("KLING_POLL_TIMEOUT", str(12 * 60)))
KLING_REQUEST_TIMEOUT = os.getenv("KLING_REQUEST_TIMEOUT")
KLING_EXTRA_HEADERS = os.getenv("KLING_EXTRA_HEADERS")

# --- Lava.top Payment ---
LAVA_WEBHOOK_SECRET = os.getenv("LAVA_WEBHOOK_SECRET")
LAVA_API_KEY = os.getenv("LAVA_API_KEY")
LAVA_FALLBACK_CHAT_ID = os.getenv("LAVA_FALLBACK_CHAT_ID", "283738604")
PAYMENT_MINI_APP_URL = f"{PUBLIC_BASE_URL.rstrip('/')}/miniapp/"

# --- Sentry (опционально) ---
SENTRY_DSN = os.getenv("SENTRY_DSN")
if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.celery import CeleryIntegration
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration(), CeleryIntegration(monitor_beat_tasks=True)],
        traces_sample_rate=0.2, send_default_pii=False,
    )
