# Generated by Django 5.2.7 on 2025-10-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_code', models.CharField(db_index=True, max_length=64)),
                ('chat_id', models.BigIntegerField()),
                ('prompt', models.TextField()),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('model', models.CharField(default='gemini-2.5-flash-image', max_length=64)),
                ('status', models.CharField(default='queued', max_length=16)),
                ('result_urls', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(db_index=True, unique=True)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
