# Generated by Django 5.2.7 on 2025-10-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0008_update_veo_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genrequest',
            name='provider_job_id',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
