# Generated by Django 5.2.7 on 2025-10-25 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0009_alter_genrequest_provider_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='genrequest',
            name='parent_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_requests', to='botapp.genrequest'),
        ),
    ]
