# Generated by Django 5.2.7 on 2025-10-25 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0007_update_video_defaults'),
        ('botapp', '0010_genrequest_parent_request'),
    ]

    operations = []
