# Generated by Django 5.2.7 on 2025-11-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0022_add_kling_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('vertex', 'Google Vertex AI'), ('veo', 'Google Veo'), ('openai', 'OpenAI Sora'), ('kling', 'Kling AI'), ('openai_image', 'OpenAI GPT Image'), ('imagen', 'Google Imagen')], max_length=20),
        ),
    ]
