# Generated by Django 5.2.7 on 2025-11-07 12:20

from django.db import migrations


def make_models_public(apps, schema_editor):
    AIModel = apps.get_model("botapp", "AIModel")
    AIModel.objects.update(min_user_level=0)


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0023_alter_aimodel_provider'),
    ]

    operations = [
        migrations.RunPython(make_models_public, migrations.RunPython.noop),
    ]
