# Generated by Django 5.2.7 on 2025-11-07 15:09

from decimal import Decimal

from django.db import migrations, models


def add_midjourney_model(apps, schema_editor):
    AIModel = apps.get_model("botapp", "AIModel")
    if AIModel.objects.filter(slug="midjourney-v6").exists():
        return
    AIModel.objects.create(
        slug="midjourney-v6",
        name="Midjourney V6",
        display_name="🎨 Midjourney (KIE.AI)",
        type="image",
        provider="midjourney",
        description="Midjourney через KIE.AI. Поддерживает text2image и image2image, а также пресеты качества/аспекта.",
        short_description="Midjourney через KIE",
        price=Decimal("79.00"),
        api_endpoint="",
        api_model_name="midjourney/v6-text-to-image",
        max_prompt_length=2500,
        supports_image_input=True,
        max_input_images=1,
        default_params={
            "aspect_ratio": "1:1",
            "quality": "standard",
        },
        allowed_params={
            "aspect_ratio": ["1:1", "16:9", "9:16", "3:2", "2:3"],
            "quality": ["standard", "high"],
            "negative_prompt": {"max_length": 2500},
            "cfg_scale": {"min": 0, "max": 1, "step": 0.1},
        },
        max_quantity=4,
        cooldown_seconds=0,
        daily_limit=None,
        is_active=True,
        order=45,
    )


def remove_midjourney_model(apps, schema_editor):
    AIModel = apps.get_model("botapp", "AIModel")
    AIModel.objects.filter(slug="midjourney-v6").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0025_switch_nano_to_gemini_vertex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('vertex', 'Google Vertex AI'), ('veo', 'Google Veo'), ('openai', 'OpenAI Sora'), ('kling', 'Kling AI'), ('midjourney', 'Midjourney (KIE)'), ('openai_image', 'OpenAI GPT Image'), ('imagen', 'Google Imagen')], max_length=20),
        ),
        migrations.RunPython(add_midjourney_model, remove_midjourney_model),
    ]
