# Generated by Django 5.2.7 on 2025-11-08 07:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


DEFAULT_RATE = Decimal('20.0')
DEFAULT_MARKUP = Decimal('2.0')


def seed_pricing_settings(apps, schema_editor):
    PricingSettings = apps.get_model('botapp', 'PricingSettings')
    if not PricingSettings.objects.exists():
        PricingSettings.objects.create(
            usd_to_token_rate=DEFAULT_RATE,
            markup_multiplier=DEFAULT_MARKUP,
        )

    AIModel = apps.get_model('botapp', 'AIModel')
    for model in AIModel.objects.all():
        price = model.price or Decimal('0')
        if not price:
            model.unit_cost_usd = Decimal('0')
        else:
            model.unit_cost_usd = (price / (DEFAULT_RATE * DEFAULT_MARKUP)).quantize(Decimal('0.0001'))
        model.save(update_fields=['unit_cost_usd'])


def delete_pricing_settings(apps, schema_editor):
    PricingSettings = apps.get_model('botapp', 'PricingSettings')
    PricingSettings.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0026_alter_aimodel_provider'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='TokenPackage',
                    fields=[
                        ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                        ('title', models.CharField(max_length=255)),
                        ('credits', models.DecimalField(decimal_places=2, max_digits=12)),
                        ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                        ('stars_amount', models.IntegerField(default=0)),
                        ('is_active', models.BooleanField(default=True)),
                        ('sort_order', models.IntegerField(default=100)),
                    ],
                    options={
                        'db_table': 'token_packages',
                        'ordering': ['sort_order', 'price_usd'],
                        'managed': False,
                    },
                )
            ],
            database_operations=[],
        ),
        migrations.CreateModel(
            name='PricingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_to_token_rate', models.DecimalField(decimal_places=4, default=Decimal('20.0000'), help_text='Сколько токенов выдаём за 1 доллар США', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('markup_multiplier', models.DecimalField(decimal_places=3, default=Decimal('2.000'), help_text='Глобальный коэффициент наценки', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pricing_settings',
                'verbose_name': 'Pricing Settings',
                'verbose_name_plural': 'Pricing Settings',
            },
        ),
        migrations.AddField(
            model_name='aimodel',
            name='unit_cost_usd',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), help_text='Себестоимость генерации в долларах США', max_digits=8),
        ),
        migrations.RunPython(seed_pricing_settings, delete_pricing_settings),
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'token_packages') THEN
                    ALTER TABLE token_packages ADD COLUMN IF NOT EXISTS price_usd numeric(10,2);
                END IF;
            END $$;
            """,
            reverse_sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'token_packages') THEN
                    ALTER TABLE token_packages DROP COLUMN IF EXISTS price_usd;
                END IF;
            END $$;
            """,
        ),
        migrations.RunSQL(
            sql=f"""
            DO $$
            BEGIN
                IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'token_packages') THEN
                    UPDATE token_packages
                    SET price_usd = ROUND(COALESCE(credits, 0) / {DEFAULT_RATE}, 2)
                    WHERE price_usd IS NULL;
                END IF;
            END $$;
            """,
            reverse_sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'token_packages') THEN
                    UPDATE token_packages SET price_usd = NULL;
                END IF;
            END $$;
            """,
        ),
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'token_packages') THEN
                    ALTER TABLE token_packages ALTER COLUMN price_usd SET NOT NULL;
                END IF;
            END $$;
            """,
            reverse_sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'token_packages') THEN
                    ALTER TABLE token_packages ALTER COLUMN price_usd DROP NOT NULL;
                END IF;
            END $$;
            """,
        ),
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION public.trg_set_ai_model_price()
            RETURNS trigger AS $$
            DECLARE
                v_rate numeric;
                v_markup numeric;
            BEGIN
                SELECT usd_to_token_rate, markup_multiplier
                INTO v_rate, v_markup
                FROM pricing_settings
                ORDER BY id
                LIMIT 1;

                IF v_rate IS NULL OR v_markup IS NULL THEN
                    RAISE EXCEPTION 'Pricing settings are not configured';
                END IF;

                NEW.price = ROUND(COALESCE(NEW.unit_cost_usd, 0) * v_rate * v_markup, 2);
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            DROP TRIGGER IF EXISTS set_ai_model_price ON botapp_aimodel;
            CREATE TRIGGER set_ai_model_price
            BEFORE INSERT OR UPDATE OF unit_cost_usd
            ON botapp_aimodel
            FOR EACH ROW
            EXECUTE FUNCTION public.trg_set_ai_model_price();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS set_ai_model_price ON botapp_aimodel;
            DROP FUNCTION IF EXISTS public.trg_set_ai_model_price();
            """,
        ),
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION public.trg_recalc_models_on_pricing()
            RETURNS trigger AS $$
            BEGIN
                UPDATE botapp_aimodel
                SET price = ROUND(unit_cost_usd * NEW.usd_to_token_rate * NEW.markup_multiplier, 2);
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            DROP TRIGGER IF EXISTS refresh_ai_model_prices ON pricing_settings;
            CREATE TRIGGER refresh_ai_model_prices
            AFTER UPDATE ON pricing_settings
            FOR EACH ROW
            EXECUTE FUNCTION public.trg_recalc_models_on_pricing();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS refresh_ai_model_prices ON pricing_settings;
            DROP FUNCTION IF EXISTS public.trg_recalc_models_on_pricing();
            """,
        ),
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'token_packages') THEN
                    CREATE OR REPLACE FUNCTION public.trg_set_token_package_credits()
                    RETURNS trigger AS $trig$
                    DECLARE
                        v_rate numeric;
                    BEGIN
                        SELECT usd_to_token_rate INTO v_rate
                        FROM pricing_settings
                        ORDER BY id
                        LIMIT 1;

                        IF v_rate IS NULL OR v_rate = 0 THEN
                            RAISE EXCEPTION 'Pricing rate is not configured';
                        END IF;

                        NEW.credits = ROUND(COALESCE(NEW.price_usd, 0) * v_rate, 2);
                        RETURN NEW;
                    END;
                    $trig$ LANGUAGE plpgsql;

                    DROP TRIGGER IF EXISTS set_token_package_credits ON token_packages;
                    CREATE TRIGGER set_token_package_credits
                    BEFORE INSERT OR UPDATE
                    ON token_packages
                    FOR EACH ROW
                    EXECUTE FUNCTION public.trg_set_token_package_credits();
                END IF;
            END $$;
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS set_token_package_credits ON token_packages;
            DROP FUNCTION IF EXISTS public.trg_set_token_package_credits();
            """,
        ),
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'token_packages') THEN
                    CREATE OR REPLACE FUNCTION public.trg_recalc_packages_on_pricing()
                    RETURNS trigger AS $trig$
                    BEGIN
                        UPDATE token_packages
                        SET credits = ROUND(price_usd * NEW.usd_to_token_rate, 2);
                        RETURN NEW;
                    END;
                    $trig$ LANGUAGE plpgsql;

                    DROP TRIGGER IF EXISTS refresh_token_packages ON pricing_settings;
                    CREATE TRIGGER refresh_token_packages
                    AFTER UPDATE ON pricing_settings
                    FOR EACH ROW
                    EXECUTE FUNCTION public.trg_recalc_packages_on_pricing();
                END IF;
            END $$;
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS refresh_token_packages ON pricing_settings;
            DROP FUNCTION IF EXISTS public.trg_recalc_packages_on_pricing();
            """,
        ),
    ]
