# Generated by Django 5.2.7 on 2025-11-08 09:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models

COST_MAP = {
    'gpt-image-1': ('image', Decimal('0.04')),
    'midjourney-v6': ('image', Decimal('0.015')),
    'nano-banana': ('image', Decimal('0.01')),
    'kling-v1': ('second', Decimal('0.042')),
    'sora2': ('second', Decimal('0.10')),
    'veo3-fast': ('second', Decimal('0.15')),
}


def populate_cost_data(apps, schema_editor):
    AIModel = apps.get_model('botapp', 'AIModel')
    for model in AIModel.objects.all():
        slug = model.slug
        if slug in COST_MAP:
            unit, cost = COST_MAP[slug]
            model.cost_unit = unit
            model.base_cost_usd = cost
            model.unit_cost_usd = cost
        else:
            model.cost_unit = model.cost_unit or 'generation'
            base = model.unit_cost_usd or Decimal('0.0000')
            model.base_cost_usd = base
        model.save(update_fields=['cost_unit', 'base_cost_usd', 'unit_cost_usd'])


def revert_cost_data(apps, schema_editor):
    AIModel = apps.get_model('botapp', 'AIModel')
    for model in AIModel.objects.all():
        model.base_cost_usd = Decimal('0.0000')
        model.cost_unit = 'generation'
        model.save(update_fields=['base_cost_usd', 'cost_unit'])


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0027_tokenpackage_pricingsettings_aimodel_unit_cost_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='base_cost_usd',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Себестоимость одной единицы (изображение/секунда)', max_digits=10),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='cost_unit',
            field=models.CharField(choices=[('image', 'Per image'), ('second', 'Per second'), ('generation', 'Per generation')], default='generation', help_text='Базовая единица тарифа для расчёта себестоимости', max_length=16),
        ),
        migrations.AddField(
            model_name='genrequest',
            name='cost_usd',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='unit_cost_usd',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Себестоимость генерации (историческое поле)', max_digits=10),
        ),
        migrations.RunPython(populate_cost_data, revert_cost_data),
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION public.trg_set_ai_model_price()
            RETURNS trigger AS $$
            DECLARE
                v_rate numeric;
                v_markup numeric;
                base_value numeric;
            BEGIN
                SELECT usd_to_token_rate, markup_multiplier
                INTO v_rate, v_markup
                FROM pricing_settings
                ORDER BY id
                LIMIT 1;

                IF v_rate IS NULL OR v_markup IS NULL THEN
                    RAISE EXCEPTION 'Pricing settings are not configured';
                END IF;

                base_value = COALESCE(NEW.base_cost_usd, NEW.unit_cost_usd, 0);
                NEW.price = ROUND(base_value * v_rate * v_markup, 2);
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            DROP TRIGGER IF EXISTS set_ai_model_price ON botapp_aimodel;
            CREATE TRIGGER set_ai_model_price
            BEFORE INSERT OR UPDATE OF unit_cost_usd, base_cost_usd
            ON botapp_aimodel
            FOR EACH ROW
            EXECUTE FUNCTION public.trg_set_ai_model_price();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS set_ai_model_price ON botapp_aimodel;
            DROP FUNCTION IF EXISTS public.trg_set_ai_model_price();
            """,
        ),
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION public.trg_recalc_models_on_pricing()
            RETURNS trigger AS $$
            BEGIN
                UPDATE botapp_aimodel
                SET price = ROUND(COALESCE(base_cost_usd, unit_cost_usd, 0) * NEW.usd_to_token_rate * NEW.markup_multiplier, 2);
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            DROP TRIGGER IF EXISTS refresh_ai_model_prices ON pricing_settings;
            CREATE TRIGGER refresh_ai_model_prices
            AFTER UPDATE ON pricing_settings
            FOR EACH ROW
            EXECUTE FUNCTION public.trg_recalc_models_on_pricing();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS refresh_ai_model_prices ON pricing_settings;
            DROP FUNCTION IF EXISTS public.trg_recalc_models_on_pricing();
            """,
        ),
    ]
