# Generated by Django 5.2.7 on 2025-11-10 12:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0028_aimodel_base_cost_usd_aimodel_cost_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_message_text', models.TextField(blank=True, default='')),
                ('last_message_type', models.CharField(blank=True, default='', max_length=32)),
                ('last_message_direction', models.CharField(blank=True, default='', max_length=16)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('unread_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_thread', to='botapp.tguser')),
            ],
            options={
                'verbose_name': 'Chat Thread',
                'verbose_name_plural': 'Chat Threads',
                'ordering': ['-last_message_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('incoming', 'Входящее'), ('outgoing', 'Исходящее')], max_length=16)),
                ('message_type', models.CharField(choices=[('text', 'Текст'), ('photo', 'Фото'), ('video', 'Видео'), ('document', 'Документ'), ('audio', 'Аудио'), ('voice', 'Голосовое'), ('sticker', 'Стикер'), ('other', 'Другое')], default='text', max_length=32)),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, default='')),
                ('media_file_id', models.CharField(blank=True, default='', max_length=255)),
                ('media_unique_id', models.CharField(blank=True, default='', max_length=255)),
                ('media_file_path', models.CharField(blank=True, default='', max_length=512)),
                ('media_file_name', models.CharField(blank=True, default='', max_length=255)),
                ('media_mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('message_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='botapp.tguser')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='botapp.chatthread')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['message_date', 'id'],
                'indexes': [models.Index(fields=['thread', 'message_date'], name='botapp_chat_thread__5b8f50_idx'), models.Index(fields=['direction', 'message_date'], name='botapp_chat_directi_c0b0ee_idx')],
            },
        ),
    ]
