from django.db import migrations


REORDER_SQL = """
ALTER TABLE IF EXISTS botapp_genrequest
    DROP CONSTRAINT IF EXISTS botapp_genrequest_ai_model_id_dc9b31a8_fk_botapp_aimodel_id;
ALTER TABLE IF EXISTS botapp_usersettings
    DROP CONSTRAINT IF EXISTS botapp_usersettings_preferred_image_mode_5c00be8e_fk_botapp_ai;
ALTER TABLE IF EXISTS botapp_usersettings
    DROP CONSTRAINT IF EXISTS botapp_usersettings_preferred_video_mode_ae833673_fk_botapp_ai;

DROP TRIGGER IF EXISTS set_ai_model_price ON botapp_aimodel;
ALTER TABLE botapp_aimodel RENAME CONSTRAINT botapp_aimodel_pkey TO botapp_aimodel_pkey_old;
ALTER TABLE botapp_aimodel RENAME CONSTRAINT botapp_aimodel_slug_key TO botapp_aimodel_slug_key_old;
DROP INDEX IF EXISTS botapp_aimodel_slug_5f06d9c7_like;

ALTER TABLE botapp_aimodel RENAME TO botapp_aimodel_old;

CREATE TABLE botapp_aimodel (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    slug varchar(50) NOT NULL,
    name varchar(100) NOT NULL,
    display_name varchar(100) NOT NULL,
    price numeric(8, 2) NOT NULL,
    base_cost_usd numeric(10, 4) NOT NULL DEFAULT 0,
    cost_unit varchar(16) NOT NULL DEFAULT 'generation',
    type varchar(10) NOT NULL,
    provider varchar(20) NOT NULL,
    description text NOT NULL,
    short_description varchar(255) NOT NULL,
    unit_cost_usd numeric(10, 4) NOT NULL DEFAULT 0,
    api_endpoint varchar(255) NOT NULL,
    api_model_name varchar(100) NOT NULL,
    max_prompt_length integer NOT NULL,
    supports_image_input boolean NOT NULL,
    max_input_images integer NOT NULL,
    default_params jsonb NOT NULL,
    allowed_params jsonb NOT NULL,
    max_quantity integer NOT NULL,
    cooldown_seconds integer NOT NULL,
    daily_limit integer NULL,
    is_active boolean NOT NULL,
    is_beta boolean NOT NULL,
    min_user_level integer NOT NULL,
    "order" integer NOT NULL,
    total_generations integer NOT NULL,
    total_errors integer NOT NULL,
    average_generation_time double precision NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT botapp_aimodel_pkey PRIMARY KEY (id),
    CONSTRAINT botapp_aimodel_slug_key UNIQUE (slug)
);

INSERT INTO botapp_aimodel (
    id,
    slug,
    name,
    display_name,
    price,
    base_cost_usd,
    cost_unit,
    type,
    provider,
    description,
    short_description,
    unit_cost_usd,
    api_endpoint,
    api_model_name,
    max_prompt_length,
    supports_image_input,
    max_input_images,
    default_params,
    allowed_params,
    max_quantity,
    cooldown_seconds,
    daily_limit,
    is_active,
    is_beta,
    min_user_level,
    "order",
    total_generations,
    total_errors,
    average_generation_time,
    created_at,
    updated_at
)
SELECT
    id,
    slug,
    name,
    display_name,
    price,
    base_cost_usd,
    cost_unit,
    type,
    provider,
    description,
    short_description,
    unit_cost_usd,
    api_endpoint,
    api_model_name,
    max_prompt_length,
    supports_image_input,
    max_input_images,
    default_params,
    allowed_params,
    max_quantity,
    cooldown_seconds,
    daily_limit,
    is_active,
    is_beta,
    min_user_level,
    "order",
    total_generations,
    total_errors,
    average_generation_time,
    created_at,
    updated_at
FROM botapp_aimodel_old;

SELECT setval(
    pg_get_serial_sequence('botapp_aimodel', 'id'),
    (SELECT MAX(id) FROM botapp_aimodel),
    true
);

DROP TABLE botapp_aimodel_old;

CREATE INDEX botapp_aimodel_slug_5f06d9c7_like
    ON botapp_aimodel (slug varchar_pattern_ops);

CREATE TRIGGER set_ai_model_price
BEFORE INSERT OR UPDATE OF unit_cost_usd, base_cost_usd
ON botapp_aimodel
FOR EACH ROW
EXECUTE FUNCTION public.trg_set_ai_model_price();

ALTER TABLE botapp_genrequest
    ADD CONSTRAINT botapp_genrequest_ai_model_id_dc9b31a8_fk_botapp_aimodel_id
    FOREIGN KEY (ai_model_id) REFERENCES botapp_aimodel(id)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE botapp_usersettings
    ADD CONSTRAINT botapp_usersettings_preferred_image_mode_5c00be8e_fk_botapp_ai
    FOREIGN KEY (preferred_image_model_id) REFERENCES botapp_aimodel(id)
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE botapp_usersettings
    ADD CONSTRAINT botapp_usersettings_preferred_video_mode_ae833673_fk_botapp_ai
    FOREIGN KEY (preferred_video_model_id) REFERENCES botapp_aimodel(id)
    DEFERRABLE INITIALLY DEFERRED;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0028_aimodel_base_cost_usd_aimodel_cost_unit_and_more'),
    ]

    operations = [
        migrations.RunSQL(REORDER_SQL, migrations.RunSQL.noop),
    ]
