# Generated by Django 5.2.7 on 2025-11-12 13:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0029_chatthread_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotErrorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'origin',
                    models.CharField(
                        choices=[
                            ('webhook', 'Telegram webhook'),
                            ('telegram_handler', 'Telegram handlers'),
                            ('celery_task', 'Celery task'),
                            ('generation', 'Generation pipeline'),
                            ('payment', 'Payments'),
                            ('miniapp', 'Miniapp/API'),
                            ('other', 'Other')
                        ],
                        default='other',
                        max_length=64
                    )
                ),
                (
                    'severity',
                    models.CharField(
                        choices=[
                            ('info', 'Info'),
                            ('warning', 'Warning'),
                            ('critical', 'Critical')
                        ],
                        default='warning',
                        max_length=16
                    )
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('new', 'New'),
                            ('in_progress', 'In progress'),
                            ('resolved', 'Resolved')
                        ],
                        db_index=True,
                        default='new',
                        max_length=16
                    )
                ),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('handler', models.CharField(blank=True, default='', max_length=255)),
                ('error_class', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('stacktrace', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('chat_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('username_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'gen_request',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='error_events',
                        to='botapp.genrequest'
                    )
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='error_events',
                        to='botapp.tguser'
                    )
                ),
            ],
            options={
                'verbose_name': 'Bot Error',
                'verbose_name_plural': 'Bot Errors',
                'ordering': ['-occurred_at', '-id'],
                'indexes': [
                    models.Index(
                        fields=['origin', 'severity', 'occurred_at'],
                        name='botapp_bote_origin_c5f40a_idx'
                    ),
                    models.Index(
                        fields=['status', 'occurred_at'],
                        name='botapp_bote_status_04d9cb_idx'
                    )
                ],
            },
        ),
    ]
